Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  # VM 1: Jenkins Master
  config.vm.define "jenkins-master" do |master|
    master.vm.hostname = "jenkins-master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "JenkinsMaster"
      vb.memory = 2048
      vb.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y openjdk-17-jdk curl gnupg docker.io git
      systemctl enable docker
      systemctl start docker
      
      # Установка Jenkins
      curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      apt update
      apt install -y jenkins
      systemctl enable jenkins
      systemctl start jenkins
    SHELL
  end

  # VM 2: Jenkins Agent
  config.vm.define "jenkins-agent" do |agent|
    agent.vm.hostname = "jenkins-agent"
    agent.vm.network "private_network", ip: "192.168.56.11"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "JenkinsAgent"
      vb.memory = 2024
      vb.cpus = 2
    end
    agent.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y openjdk-17-jdk docker.io git
      systemctl enable docker
      systemctl start docker
    SHELL
  end

end
