pipeline {
    agent any 

    environment {
        IMAGE_NAME = "pavlovskyiandrii/step_project2"
        DOCKER_HUB_CREDENTIALS = 'dockerhub-creds-id' // ID из Jenkins Cred.
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("pavlovskyiandrii/step_project2:latest", "src/")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDENTIALS}", usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_HUB_CREDENTIALS}") {
                            docker.image("${IMAGE_NAME}:latest").push()
                        }
                    }
                }
            }
        }
    }
}
