pipeline {
    agent any 

    environment {
        IMAGE_NAME = "pavlovskyiandrii/step_project2"
        DOCKER_HUB_CREDENTIALS = 'dockerhub-creds-id' // ID из Jenkins Credentials
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Pavlovskyi-Andrii/Step_project2.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDENTIALS}", usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_HUB_CREDENTIALS}") {
                            docker.image("${IMAGE_NAME}:latest").push()
                        }
                    }
                }
            }
        }
    }
}
